### ISSUE TITLE
make error: 3rdparty/poppler/git/CairoOutputDev.cc:2954:55: error: ‘class CCITTFaxStream’ has no member named ‘getEncodedByteAlign’

### ISSUE THREAD

**Issue by originrobot** [pdf2htmlEX/pdf2htmlEX#24]
Seems that the code uses deprecated CCITTFaxStream methods. Could someone tell me which version is used?

**Comment by Rockstar04** [comment]
What platform are you trying to build on? Some of us have had decent luck building on a vanilla installation of Ubuntu 18.04 with minor tweaks.

**Comment by originrobot** [comment]
I'm trying to build on ubuntu 18.04, just figured out it's poppler-0.62.0 issues. Have to change code to support it.

What's your minor tweaks to fix the issue?

Best regards,

**Comment by stephengaito** [comment]
@originrobot There is currently a working pull request #22  from my fork, [stephengaito/pdf2htmlEX](https://github.com/stephengaito/pdf2htmlEX), of this repository (While I have the ability to accept this pull request, I have not yet done so since I am still unsure how to orchestrate keeping multiple variants in the "master" repository...  and at the moment I am focusing my limited energy on getting pdf2htmlEX working on more recent Ubuntu releases... sorry :$ )

My [fork](https://github.com/stephengaito/pdf2htmlEX) of this pdf2htmlEX repository contains four branches which represent my current ongoing work on bringing pdf2htmlEX up to date on various Ubuntu releases (16.04 LTS, 18.04 LTS, 18.10 and 19.04).

The [update2poppler0_62_0ubuntu18_04 branch](https://github.com/stephengaito/pdf2htmlEX/tree/update2poppler0_62_0ubuntu18_04) **is working** and **stable** (I use it almost daily). As it suggests it is meant for use on Ubuntu 18.04.

Unfortunately the branches,  update2poppler0_68_0ubuntu18_10 and update2poppler0_74_0ubuntu19_04 currently have problems with the Font subsystem that I am trying to understand at the moment (they both seg-fault). While work on the update2poppler0_41_0ubuntu16_04 branch has not started.

SO... if you refer to the pull-request #22, you should find instructions on how to checkout and build a working pdf2htmlEX on Ubuntu 18.04.

I hope this helps.
