### ISSUE TITLE
Can't compile pdf2htmlEX in one server

### ISSUE THREAD

**Issue by Watersoul** [pdf2htmlEX/pdf2htmlEX#69]
**Hi,

I have problem with building last version just in one of 7 servers. Another 6 is ok.
Ubuntu 18.04 64-bit on all servers.**

`
-------------------------------------------------------------------
BUILDING pdf2htmlEX (using gcc)
-------------------------------------------------------------------

```
cd pdf2htmlEX
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PDF2HTMLEX_PREFIX ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'cairo>=1.10.0'
--   Found cairo, version 1.15.10
-- Trying to locate cairo-svg...
--    found cairo-svg...
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.1")
-- Performing Test CXX0X_SUPPORT
-- Performing Test CXX0X_SUPPORT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/web/git/pdf2htmlEX/pdf2htmlEX/build
make $MAKE_PARALLEL
Scanning dependencies of target pdf2htmlEX_resources
Scanning dependencies of target pdf2htmlEX
[  2%] Generating ../share/base.min.css, ../share/fancy.min.css
+ dirname ../share/build_css.sh
[  5%] Generating ../share/pdf2htmlEX.min.js
+ dirname ../share/build_js.sh
+ BASEDIR=../share
+ + CLOSURE_COMPILER_DIR=../share/../3rdparty/closure-compilerBASEDIR=../share

+ CLOSURE_COMPILER_JAR=../share/../3rdparty/closure-compiler/compiler.jar+
YUI_DIR=../share/../3rdparty/yuicompressor
+ INPUT=../share/pdf2htmlEX.js
+ + YUI_JAR=../share/../3rdparty/yuicompressor/yuicompressor-2.4.8.jarOUTPUT_FN=pdf2htmlEX.min.js

+ OUTPUT=../share/pdf2htmlEX.min.js
+ build base.css base.min.css
+ INPUT=../share/base.css
+ OUTPUT=../share/base.min.css
+ echo Building pdf2htmlEX.min.js with closure-compiler...
Building pdf2htmlEX.min.js with closure-compiler...
+ java -jar ../share/../3rdparty/closure-compiler/compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --warning_level VERBOSE --output_wrapper (function(){%output%})(); --js ../share/pdf2htmlEX.js --js_output_file ../share/pdf2htmlEX.min.js
+ echo Building ../share/base.min.css with YUI Compressor
Building ../share/base.min.css with YUI Compressor
+ java -jar ../share/../3rdparty/yuicompressor/yuicompressor-2.4.8.jar --charset utf-8 -o ../share/base.min.css ../share/base.css
[  8%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/state.cc.o
[ 20%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/draw.cc.o
[ 20%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/pdf2htmlEX.cc.o
[ 20%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/general.cc.o
[ 20%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/image.cc.o
[ 22%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/CairoBackgroundRenderer.cc.o
[ 25%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/link.cc.o
[ 31%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/outline.cc.o
[ 31%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/form.cc.o
[ 37%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o
[ 37%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/text.cc.o
[ 40%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/BackgroundRenderer.cc.o
[ 42%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/SplashBackgroundRenderer.cc.o
[ 45%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/const.cc.o
[ 48%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/encoding.cc.o
+ echo Done.
Done.
+ build fancy.css fancy.min.css
+ INPUT=../share/fancy.css
+ OUTPUT=../share/fancy.min.css
+ echo Building ../share/fancy.min.css with YUI Compressor
Building ../share/fancy.min.css with YUI Compressor
+ java -jar ../share/../3rdparty/yuicompressor/yuicompressor-2.4.8.jar --charset utf-8 -o ../share/fancy.min.css ../share/fancy.css
[ 51%] Building C object CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o
+ echo Done.
Done.
[ 54%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/math.cc.o
[ 57%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/misc.cc.o
[ 60%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/path.cc.o
[ 62%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/unicode.cc.o
[ 65%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/mingw.cc.o
[ 68%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/SignalHandler.cc.o
[ 71%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/ArgParser.cc.o
[ 74%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Base64Stream.cc.o
[ 77%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Color.cc.o
[ 80%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/DrawingTracer.cc.o
[ 82%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/CoveredTextDetector.cc.o
[ 85%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLTextLine.cc.o
[ 88%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLTextPage.cc.o
[ 91%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Preprocessor.cc.o
[ 94%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/StringFormatter.cc.o
[ 97%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/TmpFiles.cc.o
+ echo Done.
Done.
[100%] Linking CXX executable pdf2htmlEX
[100%] Built target pdf2htmlEX_resources
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `shutdownNss()':
SignatureHandler.cc:(.text+0x5): undefined reference to `NSS_Shutdown'
SignatureHandler.cc:(.text+0x19): undefined reference to `PORT_GetError'
SignatureHandler.cc:(.text+0x22): undefined reference to `PR_ErrorToString'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSignerName()':
SignatureHandler.cc:(.text+0x18c): undefined reference to `NSS_IsInitialized'
SignatureHandler.cc:(.text+0x195): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x1a1): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSignerSubjectDN()':
SignatureHandler.cc:(.text+0x1dc): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x1e8): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSigningTime()':
SignatureHandler.cc:(.text+0x24c): undefined reference to `NSS_CMSSignerInfo_GetSigningTime'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getEntityInfo(CERTNameStr*) const':
SignatureHandler.cc:(.text+0x2bc): undefined reference to `CERT_NameToAscii'
SignatureHandler.cc:(.text+0x2e9): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x2f1): undefined reference to `CERT_GetCommonName'
SignatureHandler.cc:(.text+0x31d): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x325): undefined reference to `CERT_GetCertEmailAddress'
SignatureHandler.cc:(.text+0x352): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x35a): undefined reference to `CERT_GetOrgName'
SignatureHandler.cc:(.text+0x387): undefined reference to `PORT_Free'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getCertificateInfo() const':
SignatureHandler.cc:(.text+0x3d6): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x3e2): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
SignatureHandler.cc:(.text+0x40f): undefined reference to `DER_GetInteger'
SignatureHandler.cc:(.text+0x4a3): undefined reference to `CERT_GetCertTimes'
SignatureHandler.cc:(.text+0x521): undefined reference to `CERT_ExtractPublicKey'
SignatureHandler.cc:(.text+0x868): undefined reference to `SECKEY_PublicKeyStrengthInBits'
SignatureHandler.cc:(.text+0x8d9): undefined reference to `CERT_CompareName'
SignatureHandler.cc:(.text+0x8f5): undefined reference to `SECKEY_DestroyPublicKey'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::setNSSDir(GooString const&)':
SignatureHandler.cc:(.text+0xb50): undefined reference to `NSS_IsInitialized'
SignatureHandler.cc:(.text+0xbae): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xbce): undefined reference to `SECMOD_AddNewModule'
SignatureHandler.cc:(.text+0xcf4): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xd4b): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xdcb): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xe03): undefined reference to `NSS_NoDB_Init'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::initHashContext()':
SignatureHandler.cc:(.text+0xe71): undefined reference to `NSS_CMSSignedData_GetDigestAlgs'
SignatureHandler.cc:(.text+0xe8d): undefined reference to `SECOID_FindOIDTag'
SignatureHandler.cc:(.text+0xea1): undefined reference to `SECOID_FindOIDTag'
SignatureHandler.cc:(.text+0xea8): undefined reference to `HASH_GetHashTypeByOidTag'
SignatureHandler.cc:(.text+0xeaf): undefined reference to `HASH_Create'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::~SignatureHandler()':
SignatureHandler.cc:(.text+0xefb): undefined reference to `SECITEM_FreeItem'
SignatureHandler.cc:(.text+0xf09): undefined reference to `NSS_CMSMessage_Destroy'
SignatureHandler.cc:(.text+0xf17): undefined reference to `HASH_Destroy'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::CMS_MessageCreate(SECItemStr*)':
SignatureHandler.cc:(.text+0xf4d): undefined reference to `NSS_CMSMessage_CreateFromDER'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::CMS_SignedDataCreate(NSSCMSMessageStr*)':
SignatureHandler.cc:(.text+0xf82): undefined reference to `NSS_CMSMessage_IsSigned'
SignatureHandler.cc:(.text+0xf94): undefined reference to `NSS_CMSMessage_ContentLevel'
SignatureHandler.cc:(.text+0xfa5): undefined reference to `NSS_CMSContentInfo_GetContent'
SignatureHandler.cc:(.text+0x1051): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x106a): undefined reference to `CERT_NewTempCertificate'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::SignatureHandler(unsigned char*, int)':
SignatureHandler.cc:(.text+0x1209): undefined reference to `NSS_CMSSignedData_GetSignerInfo'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::CMS_SignerInfoCreate(NSSCMSSignedDataStr*)':
SignatureHandler.cc:(.text+0x1267): undefined reference to `NSS_CMSSignedData_GetSignerInfo'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::validateSignature()':
SignatureHandler.cc:(.text+0x12c7): undefined reference to `NSS_IsInitialized'
SignatureHandler.cc:(.text+0x12e1): undefined reference to `PORT_Alloc'
SignatureHandler.cc:(.text+0x12ff): undefined reference to `HASH_End'
SignatureHandler.cc:(.text+0x130f): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x131b): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
SignatureHandler.cc:(.text+0x135e): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x139c): undefined reference to `NSS_CMSSignerInfo_Verify'
SignatureHandler.cc:(.text+0x13a8): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x13d1): undefined reference to `PORT_Free'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::validateCertificate(long)':
SignatureHandler.cc:(.text+0x1434): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x1440): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
SignatureHandler.cc:(.text+0x1467): undefined reference to `CERT_GetClassicOCSPEnabledSoftFailurePolicy'
SignatureHandler.cc:(.text+0x14a5): undefined reference to `CERT_PKIXVerifyCert'
SignatureHandler.cc:(.text+0x14aa): undefined reference to `PORT_GetError'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSignerName()':
SignatureHandler.cc:(.text+0x1b3): undefined reference to `CERT_GetCommonName'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::updateHash(unsigned char*, int)':
SignatureHandler.cc:(.text+0xeda): undefined reference to `HASH_Update'
collect2: error: ld returned 1 exit status
CMakeFiles/pdf2htmlEX.dir/build.make:906: recipe for target 'pdf2htmlEX' failed
make[2]: *** [pdf2htmlEX] Error 1
CMakeFiles/Makefile2:355: recipe for target 'CMakeFiles/pdf2htmlEX.dir/all' failed
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**If I'm trying to compile it in single thread**

`
-------------------------------------------------------------------
BUILDING pdf2htmlEX (using gcc)
-------------------------------------------------------------------

```
cd pdf2htmlEX
rm -rf build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PDF2HTMLEX_PREFIX ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'cairo>=1.10.0'
--   Found cairo, version 1.15.10
-- Trying to locate cairo-svg...
--    found cairo-svg...
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.1")
-- Performing Test CXX0X_SUPPORT
-- Performing Test CXX0X_SUPPORT - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/web/git/pdf2htmlEX/pdf2htmlEX/build
make $MAKE_PARALLEL
Scanning dependencies of target pdf2htmlEX
[  2%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/pdf2htmlEX.cc.o
[  5%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/draw.cc.o
[  8%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/general.cc.o
[ 11%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/image.cc.o
[ 14%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/font.cc.o
[ 17%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/form.cc.o
[ 20%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/link.cc.o
[ 22%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/outline.cc.o
[ 25%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/state.cc.o
[ 28%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLRenderer/text.cc.o
[ 31%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/BackgroundRenderer.cc.o
[ 34%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/SplashBackgroundRenderer.cc.o
[ 37%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/BackgroundRenderer/CairoBackgroundRenderer.cc.o
[ 40%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/const.cc.o
[ 42%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/encoding.cc.o
[ 45%] Building C object CMakeFiles/pdf2htmlEX.dir/src/util/ffw.c.o
[ 48%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/math.cc.o
[ 51%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/misc.cc.o
[ 54%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/path.cc.o
[ 57%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/unicode.cc.o
[ 60%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/mingw.cc.o
[ 62%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/util/SignalHandler.cc.o
[ 65%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/ArgParser.cc.o
[ 68%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Base64Stream.cc.o
[ 71%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Color.cc.o
[ 74%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/CoveredTextDetector.cc.o
[ 77%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/DrawingTracer.cc.o
[ 80%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLTextLine.cc.o
[ 82%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/HTMLTextPage.cc.o
[ 85%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/Preprocessor.cc.o
[ 88%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/StringFormatter.cc.o
[ 91%] Building CXX object CMakeFiles/pdf2htmlEX.dir/src/TmpFiles.cc.o
[ 94%] Linking CXX executable pdf2htmlEX
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `shutdownNss()':
SignatureHandler.cc:(.text+0x5): undefined reference to `NSS_Shutdown'
SignatureHandler.cc:(.text+0x19): undefined reference to `PORT_GetError'
SignatureHandler.cc:(.text+0x22): undefined reference to `PR_ErrorToString'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSignerName()':
SignatureHandler.cc:(.text+0x18c): undefined reference to `NSS_IsInitialized'
SignatureHandler.cc:(.text+0x195): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x1a1): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSignerSubjectDN()':
SignatureHandler.cc:(.text+0x1dc): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x1e8): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSigningTime()':
SignatureHandler.cc:(.text+0x24c): undefined reference to `NSS_CMSSignerInfo_GetSigningTime'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getEntityInfo(CERTNameStr*) const':
SignatureHandler.cc:(.text+0x2bc): undefined reference to `CERT_NameToAscii'
SignatureHandler.cc:(.text+0x2e9): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x2f1): undefined reference to `CERT_GetCommonName'
SignatureHandler.cc:(.text+0x31d): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x325): undefined reference to `CERT_GetCertEmailAddress'
SignatureHandler.cc:(.text+0x352): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x35a): undefined reference to `CERT_GetOrgName'
SignatureHandler.cc:(.text+0x387): undefined reference to `PORT_Free'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getCertificateInfo() const':
SignatureHandler.cc:(.text+0x3d6): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x3e2): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
SignatureHandler.cc:(.text+0x40f): undefined reference to `DER_GetInteger'
SignatureHandler.cc:(.text+0x4a3): undefined reference to `CERT_GetCertTimes'
SignatureHandler.cc:(.text+0x521): undefined reference to `CERT_ExtractPublicKey'
SignatureHandler.cc:(.text+0x868): undefined reference to `SECKEY_PublicKeyStrengthInBits'
SignatureHandler.cc:(.text+0x8d9): undefined reference to `CERT_CompareName'
SignatureHandler.cc:(.text+0x8f5): undefined reference to `SECKEY_DestroyPublicKey'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::setNSSDir(GooString const&)':
SignatureHandler.cc:(.text+0xb50): undefined reference to `NSS_IsInitialized'
SignatureHandler.cc:(.text+0xbae): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xbce): undefined reference to `SECMOD_AddNewModule'
SignatureHandler.cc:(.text+0xcf4): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xd4b): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xdcb): undefined reference to `NSS_Init'
SignatureHandler.cc:(.text+0xe03): undefined reference to `NSS_NoDB_Init'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::initHashContext()':
SignatureHandler.cc:(.text+0xe71): undefined reference to `NSS_CMSSignedData_GetDigestAlgs'
SignatureHandler.cc:(.text+0xe8d): undefined reference to `SECOID_FindOIDTag'
SignatureHandler.cc:(.text+0xea1): undefined reference to `SECOID_FindOIDTag'
SignatureHandler.cc:(.text+0xea8): undefined reference to `HASH_GetHashTypeByOidTag'
SignatureHandler.cc:(.text+0xeaf): undefined reference to `HASH_Create'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::~SignatureHandler()':
SignatureHandler.cc:(.text+0xefb): undefined reference to `SECITEM_FreeItem'
SignatureHandler.cc:(.text+0xf09): undefined reference to `NSS_CMSMessage_Destroy'
SignatureHandler.cc:(.text+0xf17): undefined reference to `HASH_Destroy'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::CMS_MessageCreate(SECItemStr*)':
SignatureHandler.cc:(.text+0xf4d): undefined reference to `NSS_CMSMessage_CreateFromDER'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::CMS_SignedDataCreate(NSSCMSMessageStr*)':
SignatureHandler.cc:(.text+0xf82): undefined reference to `NSS_CMSMessage_IsSigned'
SignatureHandler.cc:(.text+0xf94): undefined reference to `NSS_CMSMessage_ContentLevel'
SignatureHandler.cc:(.text+0xfa5): undefined reference to `NSS_CMSContentInfo_GetContent'
SignatureHandler.cc:(.text+0x1051): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x106a): undefined reference to `CERT_NewTempCertificate'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::SignatureHandler(unsigned char*, int)':
SignatureHandler.cc:(.text+0x1209): undefined reference to `NSS_CMSSignedData_GetSignerInfo'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::CMS_SignerInfoCreate(NSSCMSSignedDataStr*)':
SignatureHandler.cc:(.text+0x1267): undefined reference to `NSS_CMSSignedData_GetSignerInfo'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::validateSignature()':
SignatureHandler.cc:(.text+0x12c7): undefined reference to `NSS_IsInitialized'
SignatureHandler.cc:(.text+0x12e1): undefined reference to `PORT_Alloc'
SignatureHandler.cc:(.text+0x12ff): undefined reference to `HASH_End'
SignatureHandler.cc:(.text+0x130f): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x131b): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
SignatureHandler.cc:(.text+0x135e): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x139c): undefined reference to `NSS_CMSSignerInfo_Verify'
SignatureHandler.cc:(.text+0x13a8): undefined reference to `PORT_Free'
SignatureHandler.cc:(.text+0x13d1): undefined reference to `PORT_Free'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::validateCertificate(long)':
SignatureHandler.cc:(.text+0x1434): undefined reference to `CERT_GetDefaultCertDB'
SignatureHandler.cc:(.text+0x1440): undefined reference to `NSS_CMSSignerInfo_GetSigningCertificate'
SignatureHandler.cc:(.text+0x1467): undefined reference to `CERT_GetClassicOCSPEnabledSoftFailurePolicy'
SignatureHandler.cc:(.text+0x14a5): undefined reference to `CERT_PKIXVerifyCert'
SignatureHandler.cc:(.text+0x14aa): undefined reference to `PORT_GetError'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::getSignerName()':
SignatureHandler.cc:(.text+0x1b3): undefined reference to `CERT_GetCommonName'
../../poppler/build/libpoppler.a(SignatureHandler.cc.o): In function `SignatureHandler::updateHash(unsigned char*, int)':
SignatureHandler.cc:(.text+0xeda): undefined reference to `HASH_Update'
collect2: error: ld returned 1 exit status
CMakeFiles/pdf2htmlEX.dir/build.make:906: recipe for target 'pdf2htmlEX' failed
make[2]: *** [pdf2htmlEX] Error 1
CMakeFiles/Makefile2:355: recipe for target 'CMakeFiles/pdf2htmlEX.dir/all' failed
make[1]: *** [CMakeFiles/pdf2htmlEX.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**I understand that it is some problems with my server.
But I'm not skilled admin and I asking for some help.

Btw, previous version, compiled manually works fine on this server (with poppler 0.81)**

**Comment by stephengaito** [comment]
@Watersoul ,

Are you compiling using `./buildScripts/buildInstallLocallyApt` or 'just' `./buildScripts/buildPdf2htmlEX`?

The first command calls the second after previously building both poppler and fontforge.

You most definitely want to use the `./buildScripts/buildInstallLocallyApt` script in the base of a newly cloned pdf2htmlEX/pdf2htmlEX repository.

**Comment by Watersoul** [comment]
At first - ./buildScripts/buildInstallLocallyApt of course :)
Second one - just for test in single thread, after installing all dependencies
Tried many times.

Here is full log (stdout+stderr)

[log.txt](https://github.com/pdf2htmlEX/pdf2htmlEX/files/4842050/log.txt)

**Comment by stephengaito** [comment]
@Watersoul , 

Many thanks for the whole log... it is very useful (I guess there was a reason I was so careful to log everything :$ )

1. Could you post the log from one of the machines that worked?

2. I am guessing (since you have 7 servers) these are production machines which do not get re-created from absolute scratch very often... but rather get upgraded from LTS to LTS.... in which case I suspect that the machine which is failing is your *oldest* running server... is this correct?

I can see, from comparing your failing log with my successful log, that my attempt to build poppler without libnss3 has unfortunately failed (I did explicitly tell Poppler's CMake to `-DWITH_NSS=OFF` but CMake seems to have neglected this explicit request, *but* my script does not try to link against `libnss3` -- which it shouldn't be doing... but has.... ).

Before I mess with the scripts, can you confirm the above?

**Comment by Watersoul** [comment]
Thank you very much.
Sorry, was afk.

> 1. Could you post the log from one of the machines that worked?

Sure :)

> 2. I am guessing (since you have 7 servers) these are production machines which do not get re-created from absolute scratch very often... but rather get upgraded from LTS to LTS.... in which case I suspect that the machine which is failing is your _oldest_ running server... is this correct?

Of course, you are correct. Maybe not oldest, but at least, one of its. And, of course, my old servers have long LTS to LTS history. :)
 
> I can see, from comparing your failing log with my successful log, that my attempt to build poppler without libnss3 has unfortunately failed (I did explicitly tell Poppler's CMake to `-DWITH_NSS=OFF` but CMake seems to have neglected this explicit request, _but_ my script does not try to link against `libnss3` -- which it shouldn't be doing... but has.... ).
> 
> Before I mess with the scripts, can you confirm the above?

All my servers have different configurations and I have use its for different tasks, so I can't compare build process properly, but I tried :D
From time to time I need to parse up to million pdfs and I use for it this farm :)

Here is success log from my another server with long upgrade history.
[success_log.txt](https://github.com/pdf2htmlEX/pdf2htmlEX/files/4842813/success_log.txt)

**Comment by Watersoul** [comment]
I checked all servers for libnss3 and all servers have libnss3 installed.
But only one server also has libnss3-dev. And it's the server with errors:)

**Comment by Watersoul** [comment]
So, after changing poppler cmake
-DWITH_NSS=OFF
      to
 -DWITH_NSS3=OFF
all works fine :)
Thank you very much again !

**Comment by stephengaito** [comment]
@Watersoul  

Doubly Well done! I would say you have found the problem....

I will update my scripts for my next release.

Many thanks for your excellent sleuthing!

Regards,
Stephen Gaito
